apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-deploy
        image: atultripathi01/newflaskapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000