
services:
  pyhton-app:
    platform: linux/amd64
    image: atultripathi01/python-app:2.0
    build:
      context: .
    ports:
      - "8000:5000"
    volumes:
      - python_data:/var/lib/pythondata

volumes:
  python_data: {}
networks:
  localnet:
    driver: bridge